# This workflow scans the PR for secrets in its commits.
name: Scanning Credential in Commits
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, labeled]
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  run-asim-testers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        
