name: Scanning Credential in Commits
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, labeled]
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  Example-Actions-Job:
    name: Scanning for credentials in commits 
    runs-on: ubuntu-latest
    steps:
      # Display the event that triggered the workflow
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
