name: GitHub Actions Demo
on: push
jobs:
  Example-Actions-Job:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest
    steps:
      # Display the event that triggered the workflow
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
      
      # Runner information
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
      
      # Information about the repository and branch
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Get commit author email
        id: get_author_email
        run: |
          COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
          echo $COMMIT_EMAIL
      - name: Get commit author email
        id: get_author_email2
        uses: actions/github-script@v6
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            const email = commit.data.commit.author.email;
            core.setOutput('commit_email', email);    
